metadata:
  datasource:
    url: jdbc:mariadb://192.168.59.103:13306/information_schema
    password: root
    username: root

reporting:
  datasource:
    url: jdbc:vertica://192.168.59.103:15433/VMart?allowMultiQueries=true
    username: app
    password: pswd
